let champion_pool = {
    "Top": [  
    {"name": "Malphite", "tags": ["Hard CC", "Hard Engage", "Tank", "Magical", "Mid Game"]},
      {"name": "Darius", "tags": ["Hard CC", "Tank", "Physical", "Early Game", "Late Game"]},
      {"name": "Jax", "tags": ["Hard CC", "Tank", "Physical", "Mid Game"]},
      {"name": "Fiora", "tags": ["Hard CC", "Physical", "Mid Game", "Late Game"]},
      {"name": "Olaf", "tags": ["Tank", "Physical", "Early Game"]},
      {"name": "Illaoi", "tags": ["Hard Engage", "Tank", "Physical", "Early Game", "Mid Game"]},
      {"name": "Pantheon", "tags": ["Hard CC", "Hard Engage", "Physical", "Early Game", "Mid Game"]},   
      {"name": "Tryndamere", "tags": ["Physical", "Early Game", "Late Game"]},
      {"name": "Quinn", "tags": ["Physical", "Early Game", "Late Game"]},
      {"name": "Wukong", "img": "http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/MonkeyKing.png", "tags": ["Hard CC", "Hard Engage", "Physical", "Late Game"]},
      {"name": "Kayle", "tags": ["Magical", "Mid Game", "Late Game"]},
      {"name": "Camille", "tags": ["Hard CC", "Hard Engage", "Physical", "Early Game", "Late Game"]},
      {"name": "Irelia", "tags": ["Hard CC", "Tank", "Physical", "Early Game", "Late Game"]},
      {"name": "Urgot", "tags": ["Hard CC", "Hard Engage", "Physical", "Tank", "Mid Game", "Late Game"]},
      {"name": "Nasus", "tags": ["Tank", "Physical", "Late Game"]},
      {"name": "Rumble", "tags": ["Hard Engage", "Magical", "Early Game", "Mid Game", "Late Game"]},
      {"name": "Gragas", "tags": ["Hard CC", "Hard Engage", "Tank", "Magical", "Late Game"]},
      {"name": "Rengar", "tags": ["Physical", "Early Game", "Late Game"]},
      {"name": "Shaco", "tags": ["Physical", "Early Game"]},
      {"name": "Dr Mundo", "tags": ["Tank", "Magical", "Mid Game", "Late Game"]},
      {"name": "Kled", "tags": ["Hard CC", "Hard Engage", "Physical", "Mid Game"]},
      {"name": "Singed", "tags": ["Hard CC", "Tank", "Magical", "Mid Game"]},
      {"name": "Cassiopeia", "tags": ["Hard CC", "Magical", "Late Game"]},
      {"name": "Yone", "tags": ["Hard CC", "Hard Engage", "Poke", "Physical", "Early Game", "Late Game"]},
      {"name": "Riven", "tags": ["Hard CC", "Hard Engage", "Physical", "Late Game"]},
      {"name": "Sion", "tags": ["Hard CC", "Hard Engage", "Tank", "Physical", "Early Game", "Mid Game"]}
    ],

    "Mid": [
    {"name": "Aurelion Sol", "tags": ["Hard CC", "Hard Engage", "Magical", "Early Game", "Late Game"]},
      {"name": "Annie", "tags": ["Hard CC", "Hard Engage", "Magical", "Late Game"]},
      {"name": "Veigar", "tags": ["Hard CC", "Magical", "Late Game"]},
      {"name": "Ahri", "tags": ["Hard CC", "Magical", "Mid Game"]},
      {"name": "Pantheon", "tags": ["Hard CC", "Hard Engage", "Physical", "Early Game", "Mid Game"]},
      {"name": "Rumble", "tags": ["Hard Engage", "Magical", "Early Game", "Mid Game", "Late Game"]},
      {"name": "Tristana", "tags": ["Hard CC", "Physical", "Mid Game", "Late Game"]},
      {"name": "Lissandra", "tags": ["Hard CC", "Hard Engage", "Magical", "Mid Game"]},
      {"name": "Ekko", "tags": ["Hard CC", "Hard Engage", "Magical", "Early Game", "Mid Game"]},
      {"name": "Ziggs", "tags": ["Hard CC", "Poke", "Magical", "Early Game", "Mid Game"]},
      {"name": "Vel'Koz", "tags": ["Hard CC", "Poke", "Magical", "Early Game", "Mid Game"]},
      {"name": "Yasuo", "tags": ["Hard CC", "Physical", "Mid Game", "Late Game"]},
      {"name": "Kassadin", "tags": ["Magical", "Late Game"]},
      {"name": "Katarina", "tags": ["Magical", "Mid Game"]},
      {"name": "Zed", "tags": ["Physical", "Mid Game"]},
      {"name": "Fizz", "tags": ["Hard CC", "Magical", "Early Game", "Late Game"]},
      {"name": "Anivia", "tags": ["Hard CC", "Magical", "Mid Game", "Late Game"]},
      {"name": "Singed", "tags": ["Hard CC", "Tank", "Magical", "Mid Game"]},
      {"name": "Cassiopeia", "tags": ["Hard CC", "Magical", "Late Game"]},
      {"name": "Vex", "tags": ["Hard CC", "Magical", "Mid Game"]},
      {"name": "Irelia", "tags": ["Hard CC", "Tank", "Physical", "Early Game", "Late Game"]},
      {"name": "Swain", "tags": ["Hard CC", "Magical", "Mid Game"]}
    ],
    "Jungle": [   
    {"name": "Fiddlesticks", "tags": ["Hard CC", "Hard Engage", "Magical", "Early Game", "Mid Game"]},  
      {"name": "Evelynn", "tags": ["Hard CC", "Magical", "Early Game", "Late Game"]},
      {"name": "Elise", "tags": ["Hard CC", "Tank", "Magical", "Early Game", "Mid Game"]},
      {"name": "Jarvan IV", "img":"http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/JarvanIV.png", "tags": ["Hard CC", "Hard Engage", "Tank", "Physical", "Early Game", "Mid Game"]},
      {"name": "Master Yi", "tags": ["Physical", "Late Game"]},
      {"name": "Udyr", "tags": ["Hard CC", "Tank", "Late Game"]},
      {"name": "Kayn", "tags": ["Hard CC", "Physical", "Mid Game", "Late Game"]},
      {"name": "Bel'Veth", "img": "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Belveth.png", "tags": []},
      {"name": "Rammus", "tags": ["Hard CC", "Hard Engage", "Tank", "Mid Game"]},
      {"name": "Nocturne", "tags": ["Hard CC", "Hard Engage", "Physical", "Early Game"]},
      {"name": "Wukong", "img": "http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/MonkeyKing.png", "tags": ["Hard CC", "Hard Engage", "Physical", "Late Game"]},
      {"name": "Rengar", "tags": ["Physical", "Early Game", "Late Game"]},
      {"name": "Shaco", "tags": ["Physical", "Early Game"]},
      {"name": "Akali", "tags": ["Hard CC", "Magical", "Early Game"]},
      {"name": "Diana", "tags": ["Hard CC", "Poke", "Magical", "Mid Game", "Late Game"]},
      {"name": "Kha'Zix", "img":"https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Khazix.png", "tags": ["Physical", "Early Game", "Late Game"]},
      {"name": "Vi", "tags": ["Hard CC", "Hard Engage", "Physical", "Early Game", "Mid Game"]},
      {"name": "Warwick", "tags": ["Hard CC", "Tank", "Physical", "Mid Game", "Late Game"]}
      
    ],
    "Support": [  
    {"name": "Blitzcrank", "tags": ["Hard CC", "Hard Engage", "Tank", "Utility", "Early Game", "Mid Game"] },
      {"name": "Thresh", "tags": ["Hard CC", "Hard Engage", "Tank", "Utility", "Early Game", "Late Game"] },
      {"name": "Nautilus", "tags": ["Hard CC", "Hard Engage", "Tank", "Utility", "Early Game", "Late Game"] },
      {"name": "Annie", "tags": ["Hard CC", "Hard Engage", "Magical", "Late Game"] },
      {"name": "Pyke", "tags": ["Hard CC", "Hard Engage", "Physical", "Early Game", "Late Game"] },
      {"name": "Senna", "tags": ["Poke", "Physical", "Early Game", "Late Game"] },
      {"name": "Amumu", "tags": ["Hard CC", "Hard Engage", "Tank", "Magical", "Mid Game", "Late Game"] },
      {"name": "Sona", "tags": ["Hard CC", "Poke", "Magical", "Mid Game", "Late Game"] },
      {"name": "Nami", "tags": ["Hard CC", "Hard Engage", "Utility", "Early Game"] },
      {"name": "Zyra", "tags": ["Hard CC", "Hard Engage", "Poke", "Magical", "Early Game"] },
      {"name": "Maokai", "tags": ["Hard CC", "Hard Engage", "Tank", "Early Game", "Mid Game"] },
      {"name": "Alistar", "tags": ["Hard CC", "Hard Engage", "Utility", "Tank", "Mid Game"] },
      {"name": "Leona", "tags": ["Hard CC", "Hard Engage", "Tank", "Utility", "Early Game", "Mid Game"] },
      {"name": "Lulu", "tags": ["Hard CC", "Utility", "Late Game"] },
      {"name": "Karma", "tags": ["Poke", "Utility", "Early Game", "Late Game"] },
      {"name": "Soraka", "tags": ["Hard CC", "Utility", "Early Game", "Mid Game"] },
      {"name": "Rakan", "tags": ["Hard CC", "Hard Engage", "Utility", "Late Game"] },
      {"name": "Zilean", "tags": ["Utility", "Early Game", "Mid Game"] },
      {"name": "Braum", "tags": ["Hard CC", "Hard Engage", "Tank", "Utility", "Mid Game", "Late Game"] },
      {"name": "Taric", "tags": ["Hard CC", "Tank", "Utility", "Mid Game", "Late Game"] },
      {"name": "Swain", "tags": ["Hard CC", "Magical", "Mid Game"] },
      {"name": "Yuumi", "tags": ["Utility", "Late Game"] },
      {"name": "Sejuani", "tags": ["Hard CC", "Hard Engage", "Tank", "Physical", "Early Game", "Mid Game"] },
      {"name": "Renata Glasc", "img": "https://ddragon.leagueoflegends.com/cdn/13.1.1/img/champion/Renata.png", "tags": [] }

    ],
    "Bot": [
    {"name": "Xayah", "tags": ["Physical", "Mid Game", "Late Game"]},
     {"name": "Jinx", "tags": ["Physical", "Mid Game"]},
     {"name": "Draven", "tags": ["Hard CC", "Physical", "Early Game", "Mid Game"]},
     {"name": "Twitch", "tags": ["Physical", "Mid Game", "Late Game"]},
     {"name": "Kai'Sa", "tags": ["Poke", "Physical", "Early Game", "Late Game"]},
     {"name": "Sivir", "tags": ["Physical", "Mid Game"]},
     {"name": "Tristana", "tags": ["Hard CC", "Physical", "Mid Game", "Late Game"]},
     {"name": "Jhin", "tags": ["Physical", "Mid Game", "Late Game"]},
     {"name": "Kog'Maw", "img":"http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/KogMaw.png", "tags": ["Poke", "Physical", "Late Game"]},
     {"name": "Vayne", "tags": ["Hard CC", "Physical", "Late Game"]},
     {"name": "Caitlyn", "tags": ["Poke", "Physical", "Early Game", "Late Game"]},
     {"name": "Ezreal", "tags": ["Poke", "Physical", "Early Game", "Late Game"]},
     {"name": "Karthus", "tags": ["Poke", "Magical", "Late Game"]},
     {"name": "Miss Fortune", "tags": ["Physical", "Mid Game"]},
     {"name": "Varus", "tags": ["Hard CC", "Hard Engage", "Poke", "Physical", "Early Game", "Mid Game"]},
     {"name": "Samira", "tags": ["Hard CC", "Physical", "Early Game", "Mid Game"]}
    ]
  }

  export const load = () => {return {
    champion_pool
  }
}